# Generated by Django 5.2.1 on 2025-06-20 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0003_product_unit_weight_g'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '음식 카테고리',
                'verbose_name_plural': '음식 카테고리',
                'db_table': 'diet_food_category',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('calories', models.DecimalField(decimal_places=2, help_text='칼로리(Kcal)', max_digits=7)),
                ('protein', models.DecimalField(decimal_places=2, help_text='단백질(g)', max_digits=7)),
                ('carbs', models.DecimalField(decimal_places=2, help_text='탄수화물(g)', max_digits=7)),
                ('fat', models.DecimalField(decimal_places=2, help_text='지방(g)', max_digits=7)),
                ('serving_size', models.CharField(help_text='1인분 기준량(예: "100g", "1컵" 등)', max_length=50)),
                ('is_public_data', models.BooleanField(default=False, help_text='공공 API에서 가져온 데이터 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_info', to='ecommerce.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_foods', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foods', to='diet.foodcategory')),
            ],
            options={
                'db_table': 'diet_food',
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='식단 계획 이름', max_length=100)),
                ('description', models.TextField(blank=True, help_text='식단 계획 설명', null=True)),
                ('start_date', models.DateField(help_text='식단 시작일')),
                ('end_date', models.DateField(help_text='식단 종료일')),
                ('is_active', models.BooleanField(default=False, help_text='현재 활성화된 식단 여부')),
                ('total_calories', models.IntegerField(blank=True, help_text='일일 총 목표 칼로리', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meal Plan',
                'verbose_name_plural': 'Meal Plans',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MealPlanFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='식품 양 (g 또는 ml, 갯수)', max_digits=7)),
                ('meal_time', models.CharField(choices=[('breakfast', '아침'), ('lunch', '점심'), ('dinner', '저녁'), ('snack', '간식')], help_text='식사 유형', max_length=10)),
                ('food', models.ForeignKey(help_text='식단에 포함된 음식', on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_entries', to='diet.food')),
                ('meal_plan', models.ForeignKey(help_text='연결된 식단 계획', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='diet.mealplan')),
            ],
            options={
                'verbose_name': 'Meal Plan Food',
                'verbose_name_plural': 'Meal Plan Foods',
                'ordering': ['meal_plan', 'meal_time'],
            },
        ),
        migrations.CreateModel(
            name='RecommendHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', '아침'), ('lunch', '점심'), ('dinner', '저녁')], max_length=10)),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommend_histories', to='diet.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommend_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diet_recommend_history',
            },
        ),
        migrations.CreateModel(
            name='DietLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', '아침'), ('lunch', '점심'), ('dinner', '저녁'), ('snack', '간식')], max_length=10)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='섭취량(g)', max_digits=7)),
                ('recommended_at', models.DateTimeField(blank=True, help_text='추천 기반 식단 여부', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_logs', to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_logs', to='diet.food')),
            ],
            options={
                'db_table': 'diet_log',
                'indexes': [models.Index(fields=['user', 'date', 'meal_type'], name='diet_log_user_id_5670dd_idx')],
                'unique_together': {('user', 'food', 'date', 'meal_type')},
            },
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['name'], name='idx_food_name'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['is_public_data'], name='idx_food_is_public_data'),
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.CheckConstraint(condition=models.Q(('is_public_data', True), models.Q(('is_public_data', False), models.Q(('user__isnull', False), ('product__isnull', False), _connector='OR')), _connector='OR'), name='ck_food_user_or_product_not_null'),
        ),
        migrations.AlterUniqueTogether(
            name='mealplanfood',
            unique_together={('meal_plan', 'food', 'meal_time')},
        ),
        migrations.AddIndex(
            model_name='recommendhistory',
            index=models.Index(fields=['user', 'meal_type', 'recommended_at'], name='diet_recomm_user_id_fc5d4c_idx'),
        ),
    ]
