# Generated by Django 5.2.1 on 2025-06-12 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={},
        ),
    ]
