# Generated by Django 5.2.1 on 2025-06-23 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0002_alter_food_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "쉬움"), ("medium", "보통"), ("hard", "어려움")],
                default="medium",
                help_text="식단 난이도",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="다른 사용자에게 공개 여부"
            ),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="is_recommended",
            field=models.BooleanField(
                default=False, help_text="추천 식단으로 사용 가능 여부"
            ),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="likes_count",
            field=models.PositiveIntegerField(default=0, help_text="좋아요 수"),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="target_calories_max",
            field=models.IntegerField(
                blank=True, help_text="권장 최대 칼로리", null=True
            ),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="target_calories_min",
            field=models.IntegerField(
                blank=True, help_text="권장 최소 칼로리", null=True
            ),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="target_goal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weight_loss", "체중 감량"),
                    ("muscle_gain", "근육 증가"),
                    ("maintenance", "체중 유지"),
                    ("endurance", "지구력 향상"),
                    ("strength", "근력 향상"),
                    ("health", "건강 관리"),
                ],
                help_text="목표 운동 목적",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="views_count",
            field=models.PositiveIntegerField(default=0, help_text="조회수"),
        ),
        migrations.CreateModel(
            name="MealPlanLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="diet.mealplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_plan_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Meal Plan Like",
                "verbose_name_plural": "Meal Plan Likes",
                "db_table": "diet_meal_plan_like",
                "unique_together": {("user", "meal_plan")},
            },
        ),
    ]
