# Generated by Django 5.2.1 on 2025-06-13 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_alter_food_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='식단 계획 이름', max_length=100)),
                ('description', models.TextField(blank=True, help_text='식단 계획 설명', null=True)),
                ('start_date', models.DateField(help_text='식단 시작일')),
                ('end_date', models.DateField(help_text='식단 종료일')),
                ('is_active', models.BooleanField(default=False, help_text='현재 활성화된 식단 여부')),
                ('total_calories', models.IntegerField(help_text='일일 총 목표 칼로리')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meal Plan',
                'verbose_name_plural': 'Meal Plans',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MealPlanFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='식품 양 (g 또는 ml)', max_digits=7)),
                ('meal_time', models.CharField(choices=[('breakfast', '아침'), ('lunch', '점심'), ('dinner', '저녁'), ('snack', '간식')], help_text='식사 유형', max_length=10)),
                ('food', models.ForeignKey(help_text='식단에 포함된 음식', on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_entries', to='diet.food')),
                ('meal_plan', models.ForeignKey(help_text='연결된 식단 계획', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='diet.mealplan')),
            ],
            options={
                'verbose_name': 'Meal Plan Food',
                'verbose_name_plural': 'Meal Plan Foods',
                'ordering': ['meal_plan', 'meal_time'],
                'unique_together': {('meal_plan', 'food', 'meal_time')},
            },
        ),
    ]
