# Generated by Django 5.2.1 on 2025-06-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_mealplan_mealplanfood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplanfood',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='식품 양 (g 또는 ml, 갯수)', max_digits=7),
        ),
    ]
