# Generated by Django 5.2.1 on 2025-06-16 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_alter_mealplanfood_quantity'),
        ('ecommerce', '0003_alter_category_description_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_info', to='ecommerce.product'),
        ),
        migrations.AlterField(
            model_name='food',
            name='serving_size',
            field=models.CharField(help_text='1인분 기준량(예: "100g", "1컵" 등)', max_length=50),
        ),
    ]
