# Generated by Django 5.2.1 on 2025-06-16 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_alter_food_product_alter_food_serving_size'),
        ('ecommerce', '0003_alter_category_description_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='ecommerce.category'),
        ),
    ]
