# Generated by Django 5.2.1 on 2025-06-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0006_alter_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='total_calories',
            field=models.IntegerField(blank=True, help_text='일일 총 목표 칼로리', null=True),
        ),
    ]
