# Generated by Django 5.2.1 on 2025-06-18 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0007_alter_mealplan_total_calories'),
        ('ecommerce', '0003_product_unit_weight_g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foods', to='ecommerce.category'),
        ),
    ]
