# Generated by Django 5.2.1 on 2025-06-19 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0008_alter_food_category'),
        ('ecommerce', '0003_product_unit_weight_g'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='food',
            name='ck_food_user_or_product_not_null',
        ),
        migrations.AddField(
            model_name='food',
            name='is_public_data',
            field=models.BooleanField(default=False, help_text='공공 API에서 가져온 데이터 여부'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['is_public_data'], name='idx_food_is_public_data'),
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.CheckConstraint(condition=models.Q(('is_public_data', True), models.Q(('is_public_data', False), models.Q(('user__isnull', False), ('product__isnull', False), _connector='OR')), _connector='OR'), name='ck_food_user_or_product_not_null'),
        ),
    ]
