# Generated by Django 5.2.1 on 2025-06-20 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0009_remove_food_ck_food_user_or_product_not_null_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '음식 카테고리',
                'verbose_name_plural': '음식 카테고리',
                'db_table': 'diet_food_category',
            },
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foods', to='diet.foodcategory'),
        ),
        migrations.CreateModel(
            name='DietLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', '아침'), ('lunch', '점심'), ('dinner', '저녁'), ('snack', '간식')], max_length=10)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='섭취량(g)', max_digits=7)),
                ('recommended_at', models.DateTimeField(blank=True, help_text='추천 기반 식단 여부', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_logs', to='diet.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diet_log',
                'indexes': [models.Index(fields=['user', 'date', 'meal_type'], name='diet_log_user_id_5670dd_idx')],
                'unique_together': {('user', 'food', 'date', 'meal_type')},
            },
        ),
        migrations.CreateModel(
            name='RecommendHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', '아침'), ('lunch', '점심'), ('dinner', '저녁')], max_length=10)),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommend_histories', to='diet.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommend_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diet_recommend_history',
                'indexes': [models.Index(fields=['user', 'meal_type', 'recommended_at'], name='diet_recomm_user_id_fc5d4c_idx')],
            },
        ),
    ]
