# Generated by Django 5.2.1 on 2025-05-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(allow_unicode=True, max_length=100)),
                ("description", models.TextField(null=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
    ]
