# Generated by Django 5.2.1 on 2025-06-04 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0005_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(help_text="주문 당시 상품명", max_length=200),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="주문 당시 가격", max_digits=10
                    ),
                ),
                ("quantity", models.IntegerField(help_text="수량")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="ecommerce.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "주문 상품",
                "db_table": "orderitem",
            },
        ),
        migrations.CreateModel(
            name="ShippingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(help_text="받는 사람 이름", max_length=100),
                ),
                ("address_line1", models.CharField(help_text="주소", max_length=255)),
                (
                    "address_line2",
                    models.CharField(blank=True, help_text="상세 주소", max_length=255),
                ),
                ("city", models.CharField(help_text="도시", max_length=100)),
                (
                    "country",
                    models.CharField(default="Korea", help_text="국가", max_length=100),
                ),
                ("phone_number", models.CharField(help_text="전화번호", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "배송 주소",
                "db_table": "shippingaddress",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(help_text="상품명", max_length=200)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="가격", max_digits=10
                    ),
                ),
                ("quantity", models.IntegerField(help_text="수량")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ecommerce.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "장바구니 상품",
                "db_table": "cartitem",
                "unique_together": {("cart", "product")},
            },
        ),
    ]
