# Generated by Django 5.2.1 on 2025-06-04 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0006_add_shipping_orderitem_cartitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(help_text="쿠폰 코드", max_length=20, unique=True),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "퍼센트 할인"),
                            ("FIXED_AMOUNT", "고정 금액 할인"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, help_text="할인 값", max_digits=10
                    ),
                ),
                (
                    "min_purchase_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="최소 구매 금액", max_digits=10
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="최대 할인 금액",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("start_date", models.DateTimeField(help_text="사용 시작일")),
                ("end_date", models.DateTimeField(help_text="사용 종료일")),
                ("usage_limit", models.IntegerField(help_text="사용 제한 횟수")),
                (
                    "usage_count",
                    models.IntegerField(default=0, help_text="사용된 횟수"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "쿠폰",
                "db_table": "coupon",
            },
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="is_default",
            field=models.BooleanField(default=False, help_text="기본 배송지 여부"),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="장바구니 담은 시점의 상품 가격",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product_name",
            field=models.CharField(
                help_text="장바구니 담은 시점의 상품명", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="ecommerce.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="주문 시점의 상품 가격", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(help_text="주문 시점의 상품명", max_length=200),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="address_line1",
            field=models.CharField(help_text="기본 주소", max_length=200),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="address_line2",
            field=models.CharField(
                blank=True, help_text="상세 주소", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="city",
            field=models.CharField(help_text="시/도", max_length=50),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="country",
            field=models.CharField(help_text="국가", max_length=50),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="phone_number",
            field=models.CharField(help_text="연락처", max_length=20),
        ),
        migrations.AlterModelTable(
            name="cartitem",
            table="cart_item",
        ),
        migrations.AlterModelTable(
            name="orderitem",
            table="order_item",
        ),
        migrations.AlterModelTable(
            name="shippingaddress",
            table="shipping_address",
        ),
        migrations.CreateModel(
            name="PointTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(help_text="포인트 금액 (음수면 차감)")),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("EARN", "적립"),
                            ("USE", "사용"),
                            ("REFUND", "환불"),
                            ("EXPIRE", "만료"),
                            ("ADMIN", "관리자 조정"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("ORDER", "주문"),
                            ("REVIEW", "리뷰"),
                            ("SIGNUP", "회원가입"),
                            ("EVENT", "이벤트"),
                            ("ADMIN", "관리자"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="참조 ID (주문번호 등)",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("description", models.TextField(help_text="거래 설명")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "포인트 거래 내역",
                "db_table": "pointtransaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="리뷰 제목", max_length=200)),
                ("content", models.TextField(help_text="리뷰 내용")),
                (
                    "images",
                    models.TextField(
                        blank=True, help_text="리뷰 이미지 URLs", null=True
                    ),
                ),
                (
                    "is_verified_purchase",
                    models.BooleanField(default=False, help_text="구매 확인된 리뷰"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        help_text="리뷰가 작성된 주문 항목",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_reviews",
                        to="ecommerce.orderitem",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_reviews",
                        to="ecommerce.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "리뷰",
                "db_table": "review",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.IntegerField(default=0, help_text="현재 포인트 잔액"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_point",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "사용자 포인트",
                "db_table": "userpoint",
            },
        ),
        migrations.CreateModel(
            name="UserCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_used", models.BooleanField(default=False, help_text="사용 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce.coupon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_coupons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "사용자 쿠폰",
                "db_table": "usercoupon",
                "unique_together": {("user", "coupon")},
            },
        ),
    ]
