# Generated by Django 5.2.1 on 2025-06-04 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0007_coupon_remove_orderitem_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="cart_items",
        ),
        migrations.AddField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cart",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon_applied",
            field=models.CharField(
                blank=True, help_text="적용된 쿠폰 코드", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="points_applied",
            field=models.IntegerField(default=0, help_text="적용된 포인트"),
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="product",
            name="recommendations_score",
            field=models.DecimalField(
                decimal_places=2, default=0.0, help_text="추천 점수", max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.IntegerField(default=5, help_text="평점 (1-5)"),
        ),
    ]
