# Generated by Django 5.2.1 on 2025-06-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0009_bestitems_clickeditems"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clickeditems",
            name="clicked_list",
            field=models.TextField(default="[]", help_text="클릭 리스트"),
        ),
    ]
