# Generated by Django 5.2.1 on 2025-06-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0010_alter_clickeditems_clicked_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unit_weight_g",
            field=models.PositiveIntegerField(
                default=0, help_text="1팩(1단위) 무게(gram). 0이면 단위 무게 정보 없음"
            ),
        ),
    ]
