# Generated by Django 5.2.1 on 2025-06-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0011_product_unit_weight_g"),
        ("ecommerce", "0012_testproduct_alter_testmodel_product"),
    ]

    operations = []
