# Generated by Django 5.2.1 on 2025-06-22 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0013_merge_20250622_1543"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestModel",
        ),
        migrations.DeleteModel(
            name="TestProduct",
        ),
    ]
