# Generated by Django 5.2.1 on 2025-06-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0014_delete_testmodel_delete_testproduct"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpoint",
            name="user",
        ),
        migrations.DeleteModel(
            name="PointTransaction",
        ),
        migrations.DeleteModel(
            name="UserPoint",
        ),
    ]
