# Generated by Django 5.2.1 on 2025-06-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0015_remove_userpoint_user_delete_pointtransaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="is_point_purchasable",
            field=models.BooleanField(
                default=False, help_text="포인트로 구매 가능한 쿠폰 여부"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="point_cost",
            field=models.PositiveIntegerField(
                default=0, help_text="포인트로 구매 가능한 쿠폰인 경우의 포인트 비용"
            ),
        ),
    ]
