# Generated by Django 5.2.1 on 2025-06-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0016_coupon_is_point_purchasable_coupon_point_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, help_text="상품 이미지 URL", null=True),
        ),
    ]
