# Generated by Django 5.2.1 on 2025-06-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0017_product_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="price",
            field=models.PositiveIntegerField(
                help_text="장바구니 담은 시점의 상품 가격 (원 단위)"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.PositiveIntegerField(
                default=0, help_text="총 주문 금액 (원 단위)"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.PositiveIntegerField(
                help_text="주문 시점의 상품 가격 (원 단위)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(
                default=0, help_text="상품 가격 (원 단위)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sale_price",
            field=models.PositiveIntegerField(
                blank=True, help_text="할인가 (원 단위)", null=True
            ),
        ),
    ]
