# Generated by Django 5.2.1 on 2025-06-23 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0018_alter_cartitem_price_alter_order_total_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                help_text="리뷰가 작성된 주문 항목 (선택사항)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_reviews",
                to="ecommerce.orderitem",
            ),
        ),
    ]
