# Generated by Django 5.2.1 on 2025-06-11 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_checker', '0003_challengeparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challengeparticipant',
            options={'ordering': ['joined_at']},
        ),
        migrations.AlterField(
            model_name='challengeparticipant',
            name='challenge',
            field=models.ForeignKey(help_text='참가 중인 챌린지', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='challenge_checker.challenge'),
        ),
        migrations.AlterField(
            model_name='challengeparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to=settings.AUTH_USER_MODEL),
        ),
    ]
