# Generated by Django 5.2.1 on 2025-06-22 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                help_text="챌린지 생성자 (개인 챌린지의 경우)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_challenges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="is_personal",
            field=models.BooleanField(
                default=False, help_text="개인 챌린지 여부 (True: 개인, False: 공개)"
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "진행중"),
                    ("completed", "완료"),
                    ("inactive", "비활성"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="target_value",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="목표값 (goal_value와 중복이지만 호환성을 위해 유지)",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="PointTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(help_text="증감된 포인트 (음수 가능)")),
                (
                    "reason",
                    models.CharField(
                        blank=True, help_text="포인트 증감 사유", max_length=200
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        blank=True,
                        help_text="발생 원인이 된 챌린지 (챌린지 관련 포인트인 경우)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="challenge.challenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "value",
                    models.IntegerField(
                        help_text="기록된 값 (운동 횟수, 칼로리, 거리 등)"
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("workout_count", "운동 횟수"),
                            ("calories", "칼로리"),
                            ("distance", "거리"),
                            ("other", "기타"),
                        ],
                        default="workout_count",
                        help_text="로그 유형",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="메모")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="challenge_u_user_id_827e88_idx"
                    ),
                    models.Index(
                        fields=["user", "log_type"],
                        name="challenge_u_user_id_4532db_idx",
                    ),
                ],
            },
        ),
    ]
