# Generated by Django 5.2.1 on 2025-06-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0002_challenge_creator_challenge_is_personal_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PointTransaction",
        ),
    ]
