# Generated by Django 5.2.1 on 2025-06-22 11:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0003_delete_pointtransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="entry_cost",
            field=models.PositiveIntegerField(
                default=100, help_text="챌린지 참여에 필요한 포인트"
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="min_participants",
            field=models.PositiveIntegerField(
                default=5, help_text="챌린지 시작에 필요한 최소 참여자 수"
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="reward_multiplier",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("1.5"),
                help_text="참여자 수에 따른 보상 배수",
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name="challengeparticipant",
            name="entry_points_paid",
            field=models.PositiveIntegerField(
                default=0, help_text="참여 시 지불한 포인트"
            ),
        ),
        migrations.AddField(
            model_name="challengeparticipant",
            name="reward_points_earned",
            field=models.PositiveIntegerField(
                default=0, help_text="완료 시 획득한 보상 포인트"
            ),
        ),
    ]
