# Generated by Django 5.2.1 on 2025-06-10 08:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("strength", "근력 운동"),
                            ("cardio", "유산소 운동"),
                            ("flexibility", "유연성 운동"),
                            ("balance", "밸런스 운동"),
                            ("endurance", "지구력 운동"),
                            ("hiit", "HIIT"),
                            ("yoga", "요가"),
                            ("pilates", "필라테스"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="운동 타입",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "color_code",
                    models.CharField(
                        default="#000000", max_length=7, verbose_name="색상 코드"
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=100, verbose_name="아이콘"),
                ),
            ],
            options={
                "verbose_name": "운동 타입",
                "verbose_name_plural": "운동 타입",
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="운동명"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "muscle_groups",
                    models.CharField(max_length=500, verbose_name="주요 근육군"),
                ),
                (
                    "equipment_needed",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="필요 장비"
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "초급"),
                            ("intermediate", "중급"),
                            ("advanced", "고급"),
                        ],
                        db_index=True,
                        default="beginner",
                        max_length=20,
                        verbose_name="난이도",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="운동 방법"),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, verbose_name="시연 영상 URL"),
                ),
                (
                    "calories_per_minute",
                    models.PositiveIntegerField(
                        default=5, verbose_name="분당 칼로리 소모량"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 상태"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "운동",
                "verbose_name_plural": "운동",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["difficulty_level"],
                        name="workouts_ex_difficu_8eff39_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="workouts_ex_is_acti_ffaadc_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkoutRoutine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="루틴명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "초급"),
                            ("intermediate", "중급"),
                            ("advanced", "고급"),
                        ],
                        db_index=True,
                        default="beginner",
                        max_length=20,
                        verbose_name="난이도",
                    ),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        help_text="분 단위", verbose_name="예상 소요시간"
                    ),
                ),
                (
                    "target_muscle_groups",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="목표 근육군"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="공개 여부"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="추천 루틴"
                    ),
                ),
                (
                    "is_template",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="템플릿 루틴"
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(default=0, verbose_name="사용 횟수"),
                ),
                (
                    "rating_sum",
                    models.PositiveIntegerField(default=0, verbose_name="평점 합계"),
                ),
                (
                    "rating_count",
                    models.PositiveIntegerField(default=0, verbose_name="평점 개수"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_routines",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "운동 루틴",
                "verbose_name_plural": "운동 루틴",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(db_index=True, verbose_name="시작 시간"),
                ),
                ("end_time", models.DateTimeField(verbose_name="종료 시간")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(verbose_name="운동 시간(분)"),
                ),
                (
                    "calories_burned",
                    models.PositiveIntegerField(verbose_name="소모 칼로리"),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="1-5점 평가",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="만족도",
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("excellent", "최고"),
                            ("good", "좋음"),
                            ("normal", "보통"),
                            ("tired", "피곤"),
                            ("bad", "나쁨"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="컨디션",
                    ),
                ),
                (
                    "workout_type",
                    models.CharField(
                        choices=[
                            ("strength", "근력 운동"),
                            ("cardio", "유산소 운동"),
                            ("flexibility", "유연성 운동"),
                            ("hiit", "HIIT"),
                            ("yoga", "요가"),
                        ],
                        db_index=True,
                        default="strength",
                        max_length=50,
                        verbose_name="운동 타입",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="운동 메모")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workout_logs",
                        to="workouts.workoutroutine",
                        verbose_name="사용된 루틴",
                    ),
                ),
            ],
            options={
                "verbose_name": "운동 기록",
                "verbose_name_plural": "운동 기록",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="RoutineExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sets", models.PositiveIntegerField(verbose_name="세트 수")),
                ("reps", models.PositiveIntegerField(verbose_name="반복 횟수")),
                (
                    "weight",
                    models.FloatField(
                        blank=True,
                        help_text="해당하는 경우만",
                        null=True,
                        verbose_name="무게(kg)",
                    ),
                ),
                (
                    "rest_time",
                    models.PositiveIntegerField(
                        default=60, verbose_name="세트간 휴식시간(초)"
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="순서")),
                ("notes", models.TextField(blank=True, verbose_name="특이사항")),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routine_exercises",
                        to="workouts.exercise",
                        verbose_name="운동",
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routine_exercises",
                        to="workouts.workoutroutine",
                        verbose_name="루틴",
                    ),
                ),
            ],
            options={
                "verbose_name": "루틴 운동",
                "verbose_name_plural": "루틴 운동",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_workouts",
                    models.PositiveIntegerField(default=0, verbose_name="총 운동 횟수"),
                ),
                (
                    "total_duration_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="총 운동 시간(분)"
                    ),
                ),
                (
                    "total_calories_burned",
                    models.PositiveIntegerField(
                        default=0, verbose_name="총 소모 칼로리"
                    ),
                ),
                (
                    "average_rating",
                    models.FloatField(default=0.0, verbose_name="평균 만족도"),
                ),
                (
                    "favorite_mood",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="주요 컨디션"
                    ),
                ),
                (
                    "longest_workout_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="최장 운동시간(분)"
                    ),
                ),
                (
                    "current_streak_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="현재 연속 운동일"
                    ),
                ),
                (
                    "max_streak_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="최대 연속 운동일"
                    ),
                ),
                (
                    "last_workout_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="마지막 운동일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="갱신일"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_stats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "운동 통계",
                "verbose_name_plural": "운동 통계",
            },
        ),
        migrations.CreateModel(
            name="WorkoutLogExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sets_completed",
                    models.PositiveIntegerField(verbose_name="완료한 세트 수"),
                ),
                (
                    "reps_completed",
                    models.PositiveIntegerField(verbose_name="완료한 반복 횟수"),
                ),
                (
                    "weight_used",
                    models.FloatField(
                        blank=True, null=True, verbose_name="사용한 무게(kg)"
                    ),
                ),
                (
                    "rest_time_actual",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="실제 휴식시간(초)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="운동별 메모")),
                ("order", models.PositiveIntegerField(verbose_name="운동 순서")),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workouts.exercise",
                        verbose_name="운동",
                    ),
                ),
                (
                    "workout_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_exercises",
                        to="workouts.workoutlog",
                        verbose_name="운동 로그",
                    ),
                ),
            ],
            options={
                "verbose_name": "운동 로그 상세",
                "verbose_name_plural": "운동 로그 상세",
                "ordering": ["order"],
                "indexes": [
                    models.Index(
                        fields=["workout_log", "order"],
                        name="workouts_wo_workout_0a8d9a_idx",
                    )
                ],
                "unique_together": {("workout_log", "order")},
            },
        ),
        migrations.AddIndex(
            model_name="workoutroutine",
            index=models.Index(
                fields=["user", "-created_at"], name="workouts_wo_user_id_2e4cee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workoutroutine",
            index=models.Index(
                fields=["is_public", "is_featured"],
                name="workouts_wo_is_publ_185a8c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workoutroutine",
            index=models.Index(
                fields=["difficulty_level"], name="workouts_wo_difficu_36f27a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workoutlog",
            index=models.Index(
                fields=["user", "-start_time"], name="workouts_wo_user_id_490a96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workoutlog",
            index=models.Index(
                fields=["start_time"], name="workouts_wo_start_t_857cb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workoutlog",
            index=models.Index(fields=["rating"], name="workouts_wo_rating_e6d5fb_idx"),
        ),
        migrations.AddIndex(
            model_name="workoutlog",
            index=models.Index(fields=["mood"], name="workouts_wo_mood_370cb5_idx"),
        ),
        migrations.AddIndex(
            model_name="routineexercise",
            index=models.Index(
                fields=["routine", "order"], name="workouts_ro_routine_5bb7c0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="routineexercise",
            unique_together={("routine", "order")},
        ),
    ]
