# Generated by Django 5.2.1 on 2025-06-20 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutroutine",
            name="copied_from",
            field=models.ForeignKey(
                blank=True,
                help_text="다른 사용자의 루틴을 복사한 경우 원본 루틴을 저장",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copied_routines",
                to="workouts.workoutroutine",
                verbose_name="복사된 원본 루틴",
            ),
        ),
    ]
