# Generated by Django 5.2.1 on 2025-06-20 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_workoutroutine_copied_from"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "진행 중"),
                            ("paused", "일시정지"),
                            ("completed", "완료"),
                            ("cancelled", "취소"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="세션 상태",
                    ),
                ),
                (
                    "current_exercise_index",
                    models.PositiveIntegerField(
                        default=0, verbose_name="현재 운동 인덱스"
                    ),
                ),
                (
                    "current_set",
                    models.PositiveIntegerField(default=1, verbose_name="현재 세트"),
                ),
                (
                    "session_start_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="세션 시작 시간"
                    ),
                ),
                (
                    "session_end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="세션 종료 시간"
                    ),
                ),
                (
                    "total_rest_time",
                    models.PositiveIntegerField(
                        default=0, verbose_name="총 휴식 시간(초)"
                    ),
                ),
                (
                    "total_workout_time",
                    models.PositiveIntegerField(
                        default=0, verbose_name="총 운동 시간(초)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="세션 메모")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_sessions",
                        to="workouts.workoutroutine",
                        verbose_name="운동 루틴",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "운동 세션",
                "verbose_name_plural": "운동 세션",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionExerciseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_number", models.PositiveIntegerField(verbose_name="세트 번호")),
                (
                    "reps_completed",
                    models.PositiveIntegerField(verbose_name="완료된 반복 횟수"),
                ),
                (
                    "weight_used",
                    models.FloatField(
                        blank=True, null=True, verbose_name="사용된 무게(kg)"
                    ),
                ),
                (
                    "rest_start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="휴식 시작 시간"
                    ),
                ),
                (
                    "rest_end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="휴식 종료 시간"
                    ),
                ),
                (
                    "exercise_start_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="운동 시작 시간"
                    ),
                ),
                (
                    "exercise_end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="운동 완료 시간"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="완료 여부"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="세트별 메모")),
                (
                    "routine_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workouts.routineexercise",
                        verbose_name="루틴 운동",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_logs",
                        to="workouts.workoutsession",
                        verbose_name="운동 세션",
                    ),
                ),
            ],
            options={
                "verbose_name": "세션 운동 로그",
                "verbose_name_plural": "세션 운동 로그",
                "ordering": ["set_number"],
            },
        ),
        migrations.AddIndex(
            model_name="workoutsession",
            index=models.Index(
                fields=["user", "-created_at"], name="workouts_wo_user_id_da4c14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workoutsession",
            index=models.Index(fields=["status"], name="workouts_wo_status_e8689a_idx"),
        ),
        migrations.AddIndex(
            model_name="sessionexerciselog",
            index=models.Index(
                fields=["session", "routine_exercise"],
                name="workouts_se_session_64a277_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sessionexerciselog",
            unique_together={("session", "routine_exercise", "set_number")},
        ),
    ]
