# Generated by Django 5.2.1 on 2025-06-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0003_workoutsession_sessionexerciselog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="routineexercise",
            name="max_exercise_time",
            field=models.PositiveIntegerField(
                default=180,
                help_text="각 세트당 최대 운동 허용 시간",
                verbose_name="세트별 최대 운동시간(초)",
            ),
        ),
    ]
