<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-06-03 05:49
=======
# Generated by Django 5.2.1 on 2025-06-13 04:53
>>>>>>> origin/back-feat-cr-perm-1

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=3000)),
                ('content_category', models.CharField(choices=[('fitness_tip', '운동 팁'), ('question_answer', '질문 답변'), ('certification_review', '인증 후기'), ('free_board', '자유 게시판')], max_length=20)),
                ('content_image', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
=======
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
>>>>>>> origin/back-feat-cr-perm-1
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.post')),
            ],
=======
            name='RoutineSharePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'View Only'), ('edit', 'Edit'), ('admin', 'Owner/Admin')], default='view', help_text='부여된 권한 레벨', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, help_text='권한을 부여한 사용자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_share_permissions', to=settings.AUTH_USER_MODEL)),
                ('routine', models.ForeignKey(help_text='공유 권한을 부여할 대상 루틴', on_delete=django.db.models.deletion.CASCADE, related_name='share_permissions', to='community.routine')),
                ('user', models.ForeignKey(help_text='이 루틴에 접근 권한을 갖는 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='routine_share_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '루틴 공유 권한',
                'verbose_name_plural': '루틴 공유 권한 목록',
                'ordering': ['-created_at'],
                'unique_together': {('routine', 'user')},
            },
>>>>>>> origin/back-feat-cr-perm-1
        ),
    ]
