# Generated by Django 5.2.1 on 2025-06-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='is_public',
            field=models.BooleanField(default=False, help_text='공개 상태 (True면 누구나 조회 가능)'),
        ),
    ]
