# Generated by Django 5.2.1 on 2025-06-20 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_commentlike_postlike"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Routine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="공개 상태 (True면 누구나 조회 가능)"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoutineShareLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="공유 URL 토큰",
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="링크 생성 시각"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="링크 만료 시각 (미설정 시 무제한)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="활성화 여부 (False면 접근 차단)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="링크를 생성한 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_share_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        help_text="공유 링크를 생성할 루틴",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to="community.routine",
                    ),
                ),
            ],
            options={
                "verbose_name": "루틴 공유 링크",
                "verbose_name_plural": "루틴 공유 링크 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoutineSharePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("view", "View Only"),
                            ("edit", "Edit"),
                            ("admin", "Owner/Admin"),
                        ],
                        default="view",
                        help_text="부여된 권한 레벨",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="권한을 부여한 사용자",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_share_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        help_text="공유 권한을 부여할 대상 루틴",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_permissions",
                        to="community.routine",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="이 루틴에 접근 권한을 갖는 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routine_share_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "루틴 공유 권한",
                "verbose_name_plural": "루틴 공유 권한 목록",
                "ordering": ["-created_at"],
                "unique_together": {("routine", "user")},
            },
        ),
    ]
