# Generated by Django 5.2.1 on 2025-06-19 06:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_routine_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='공유 URL 토큰', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='링크 생성 시각')),
                ('expires_at', models.DateTimeField(blank=True, help_text='링크 만료 시각 (미설정 시 무제한)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부 (False면 접근 차단)')),
                ('created_by', models.ForeignKey(help_text='링크를 생성한 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='created_share_links', to=settings.AUTH_USER_MODEL)),
                ('routine', models.ForeignKey(help_text='공유 링크를 생성할 루틴', on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='community.routine')),
            ],
            options={
                'verbose_name': '루틴 공유 링크',
                'verbose_name_plural': '루틴 공유 링크 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
