# Generated by Django 5.2.1 on 2025-05-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', '비활동적'), ('light', '가벼운 활동'), ('moderate', '보통 활동'), ('active', '활발한 활동'), ('very_active', '매우 활발한 활동')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fitness_goal',
            field=models.CharField(blank=True, choices=[('weight_loss', '체중 감량'), ('muscle_gain', '근육 증가'), ('maintenance', '체중 유지'), ('endurance', '지구력 향상'), ('strenght', '근력 향상')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', '남성'), ('f', '여성'), ('o', '기타')], max_length=1, null=True),
        ),
    ]
