# Generated by Django 5.2.1 on 2025-06-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='target_calories',
            field=models.IntegerField(default=2000, help_text='목표 칼로리 (Kcal)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_carbs',
            field=models.DecimalField(decimal_places=2, default=250.0, help_text='목표 탄수화물 (g)', max_digits=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_fat',
            field=models.DecimalField(decimal_places=2, default=70.0, help_text='목표 지방 (g)', max_digits=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_protein',
            field=models.DecimalField(decimal_places=2, default=75.0, help_text='목표 단백질 (g)', max_digits=7),
        ),
    ]
