# Generated by Django 5.2.1 on 2025-06-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_userprofile_target_calories_userprofile_target_carbs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="onboarding_completed",
            field=models.BooleanField(default=False, help_text="온보딩 완료 여부"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="onboarding_completed_at",
            field=models.DateTimeField(
                blank=True, help_text="온보딩 완료 시간", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="onboarding_data",
            field=models.JSONField(
                blank=True, help_text="온보딩 데이터 (JSON 형태)", null=True
            ),
        ),
    ]
