# Generated by Django 5.2.1 on 2025-06-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_userprofile_onboarding_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="points",
            field=models.PositiveIntegerField(default=0, help_text="누적 포인트"),
        ),
    ]
