# Generated by Django 5.2.1 on 2025-06-23 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingdata",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("m", "남성"), ("f", "여성"), ("o", "기타")],
                max_length=1,
                null=True,
                verbose_name="성별",
            ),
        ),
        migrations.AddField(
            model_name="onboardingdata",
            name="target_calories",
            field=models.PositiveIntegerField(
                default=2000,
                validators=[
                    django.core.validators.MinValueValidator(1200),
                    django.core.validators.MaxValueValidator(4000),
                ],
                verbose_name="목표 칼로리 (kcal/day)",
            ),
        ),
    ]
