# Generated by Django 5.2.1 on 2025-06-22 08:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PointPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("CHALLENGE_COMPLETION", "챌린지 완료"),
                            ("ORDER_PURCHASE", "주문 구매"),
                            ("REVIEW_WRITE", "리뷰 작성"),
                            ("SIGNUP_BONUS", "회원가입 보너스"),
                            ("SOCIAL_SHARE", "소셜 공유"),
                            ("EVENT_PARTICIPATION", "이벤트 참여"),
                        ],
                        help_text="정책 유형",
                        max_length=25,
                        unique=True,
                    ),
                ),
                (
                    "points_amount",
                    models.IntegerField(help_text="지급/차감 포인트 (고정값인 경우)"),
                ),
                (
                    "percentage_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="적립률 (퍼센트, 예: 5.00 = 5%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "min_amount",
                    models.IntegerField(default=0, help_text="최소 적립/차감 포인트"),
                ),
                (
                    "max_amount",
                    models.IntegerField(
                        blank=True, help_text="최대 적립/차감 포인트", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="정책 활성화 여부"),
                ),
                ("description", models.TextField(blank=True, help_text="정책 설명")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "포인트 정책",
                "verbose_name_plural": "포인트 정책",
                "db_table": "point_policy",
            },
        ),
        migrations.CreateModel(
            name="PointTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="포인트 금액 (양수: 적립, 음수: 차감)"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("EARN", "적립"),
                            ("USE", "사용"),
                            ("REFUND", "환불"),
                            ("EXPIRE", "만료"),
                            ("ADMIN", "관리자 조정"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("CHALLENGE", "챌린지"),
                            ("ORDER", "주문"),
                            ("REVIEW", "리뷰"),
                            ("SIGNUP", "회원가입"),
                            ("EVENT", "이벤트"),
                            ("SOCIAL_SHARE", "소셜 공유"),
                            ("ADMIN", "관리자"),
                            ("OTHER", "기타"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="참조 ID (주문번호, 챌린지ID 등)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("description", models.TextField(help_text="거래 설명")),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="관련 객체 ID", null=True
                    ),
                ),
                ("balance_after", models.IntegerField(help_text="거래 후 포인트 잔액")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="관련 객체 타입",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_point_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "포인트 거래내역",
                "verbose_name_plural": "포인트 거래내역",
                "db_table": "point_transaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PointExpiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_amount", models.IntegerField(help_text="만료될 포인트")),
                ("earned_date", models.DateTimeField(help_text="포인트 적립일")),
                ("expiry_date", models.DateTimeField(help_text="포인트 만료일")),
                (
                    "is_expired",
                    models.BooleanField(default=False, help_text="만료 처리 여부"),
                ),
                (
                    "expired_at",
                    models.DateTimeField(
                        blank=True, help_text="실제 만료 처리 일시", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_expiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_transaction",
                    models.ForeignKey(
                        help_text="포인트를 적립한 원본 거래",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expiry_records",
                        to="points.pointtransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "포인트 만료",
                "verbose_name_plural": "포인트 만료",
                "db_table": "point_expiry",
                "ordering": ["expiry_date"],
            },
        ),
        migrations.CreateModel(
            name="UserPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.IntegerField(
                        default=0,
                        help_text="현재 포인트 잔액",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_balance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 포인트",
                "verbose_name_plural": "사용자 포인트",
                "db_table": "user_point",
            },
        ),
        migrations.AddIndex(
            model_name="pointtransaction",
            index=models.Index(
                fields=["user", "created_at"], name="point_trans_user_id_dfea0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pointtransaction",
            index=models.Index(
                fields=["user", "transaction_type"],
                name="point_trans_user_id_88226f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pointtransaction",
            index=models.Index(
                fields=["reference_type", "reference_id"],
                name="point_trans_referen_ac4168_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pointexpiry",
            index=models.Index(
                fields=["user", "expiry_date"], name="point_expir_user_id_48207d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pointexpiry",
            index=models.Index(
                fields=["is_expired", "expiry_date"],
                name="point_expir_is_expi_048280_idx",
            ),
        ),
    ]
