# Generated by Django 5.2.1 on 2025-06-10 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('create', '생성'), ('update', '수정'), ('delete', '삭제')], max_length=10)),
                ('field_changes', models.JSONField(default=dict)),
                ('previous_data', models.JSONField(default=dict)),
                ('current_data', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client_timestamp', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', '동기화 대기'), ('synced', '동기화 완료'), ('failed', '동기화 실패'), ('conflict', '충돌 발생')], default='pending', max_length=10)),
                ('sync_timestamp', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('conflict_resolution', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'content_type', 'timestamp'], name='audit_chang_user_id_7fddb0_idx'), models.Index(fields=['sync_status'], name='audit_chang_sync_st_1db21e_idx')],
            },
        ),
    ]
